services:
  app:
    image: gg-client
    container_name: gg-client
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5050:3000"
    build:
      context: .
      dockerfile: Dockerfile