export const ENABLED_PAYMENT = process.env.NEXT_PUBLIC_ENABLED_PAYMENT || '';
export const ALTERNATIVE_CATEGORIES = process.env.NEXT_PUBLIC_ALTERNATIVE_CATEGORIES || '';
export const DOMAIN_NAME = process.env.NEXT_PUBLIC_DOMAIN_NAME || '';